In [20]:
import pandas as pd

In [21]:
df= pd.read_csv('data.csv')

In [22]:
df.head()

age  fever  cough  shortness of breath  sore throat  muscle pain  nausea  \
0   28      1      1                    1            0            0       0   
1   51      1      1                    1            0            0       0   
2   37      1      0                    0            0            0       0   
3   35      1      0                    0            0            0       0   
4   45      1      0                    0            0            0       0   

   diarrhoea  fatigue  vomiting  headache  output  
0          0        0         0         0       1  
1          0        0         0         0       1  
2          0        0         0         0       0  
3          0        0         0         0       0  
4          0        0         0         0       0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  270 non-null    int64
 1   fever                270 non-null    int64
 2   cough                270 non-null    int64
 3   shortness of breath  270 non-null    int64
 4   sore throat          270 non-null    int64
 5   muscle pain          270 non-null    int64
 6   nausea               270 non-null    int64
 7   diarrhoea            270 non-null    int64
 8   fatigue              270 non-null    int64
 9   vomiting             270 non-null    int64
 10  headache             270 non-null    int64
 11  output               270 non-null    int64
dtypes: int64(12)
memory usage: 25.4 KB


In [24]:
df.describe()

age       fever       cough  shortness of breath  sore throat  \
count  270.000000  270.000000  270.000000           270.000000   270.000000   
mean    53.148148    0.751852    0.437037             0.059259     0.118519   
std     17.436030    0.432740    0.496941             0.236548     0.323821   
min      4.000000    0.000000    0.000000             0.000000     0.000000   
25%     44.250000    1.000000    0.000000             0.000000     0.000000   
50%     55.000000    1.000000    0.000000             0.000000     0.000000   
75%     65.000000    1.000000    1.000000             0.000000     0.000000   
max     89.000000    1.000000    1.000000             1.000000     1.000000   

       muscle pain      nausea   diarrhoea     fatigue    vomiting  \
count   270.000000  270.000000  270.000000  270.000000  270.000000   
mean      0.077778    0.096296    0.044444    0.040741    0.022222   
std       0.268319    0.295545    0.206463    0.198056    0.147679   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       0.000000    0.000000    0.000000    0.000000    0.000000   
50%       0.000000    0.000000    0.000000    0.000000    0.000000   
75%       0.000000    0.000000    0.000000    0.000000    0.000000   
max       1.000000    1.000000    1.000000    1.000000    1.000000   

         headache      output  
count  270.000000  270.000000  
mean     0.059259    0.529630  
std      0.236548    0.500048  
min      0.000000    0.000000  
25%      0.000000    0.000000  
50%      0.000000    1.000000  
75%      0.000000    1.000000  
max      1.000000    1.000000

In [25]:
import numpy as np

In [26]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

    

In [27]:
np.random.permutation(7)

array([5, 4, 1, 6, 2, 3, 0])

In [28]:
train, test = data_split(df,0.2)

In [29]:
train

age  fever  cough  shortness of breath  sore throat  muscle pain  nausea  \
115   75      1      0                    0            0            0       0   
33    65      0      0                    1            0            0       0   
184   55      0      0                    0            0            0       0   
142   65      1      0                    0            1            1       0   
197   35      1      1                    0            0            0       0   
..   ...    ...    ...                  ...          ...          ...     ...   
20    75      1      0                    0            0            0       0   
188   70      1      0                    0            0            0       0   
71    65      1      0                    0            0            0       0   
106   65      1      0                    0            0            0       0   
102   35      1      0                    0            1            0       0   

     diarrhoea  fatigue  vomiting  headache  output  
115          0        0         0         0       0  
33           0        1         0         0       1  
184          0        0         0         0       0  
142          0        0         0         0       1  
197          0        0         0         0       0  
..         ...      ...       ...       ...     ...  
20           0        0         0         0       0  
188          0        0         0         0       1  
71           0        1         1         0       1  
106          0        1         0         0       1  
102          0        0         0         0       1  

[216 rows x 12 columns]

In [30]:
test

age  fever  cough  shortness of breath  sore throat  muscle pain  nausea  \
30    55      1      0                    0            0            0       0   
116   25      1      0                    0            0            0       0   
79    55      0      0                    0            0            0       0   
127   75      1      1                    0            0            0       1   
196   65      0      1                    1            0            0       0   
137   60      1      1                    0            0            0       1   
209   33      1      0                    0            0            1       0   
45    55      1      1                    0            0            0       1   
158   37      0      0                    0            0            0       0   
247   70      0      1                    1            0            0       0   
183   55      1      0                    0            0            0       0   
268   22      1      0                    0            1            0       0   
227   47      1      0                    0            0            0       0   
82    65      1      1                    0            0            0       0   
165   47      1      0                    0            0            0       0   
194   55      0      1                    0            0            0       0   
226   63      1      1                    0            0            0       0   
146   35      1      0                    0            0            1       0   
104   25      0      1                    0            0            0       1   
60     5      1      0                    0            0            0       0   
221   33      1      1                    0            1            0       0   
266   44      1      1                    0            1            0       0   
46    75      1      1                    0            0            0       0   
42    35      1      0                    0            0            0       0   
185   50      0      1                    0            0            0       0   
9     55      1      0                    0            0            0       0   
22    25      1      1                    0            0            0       0   
199   45      1      1                    0            0            0       0   
109   65      1      0                    0            0            0       0   
24    65      0      1                    0            0            1       0   
113   55      1      0                    0            0            0       0   
68    25      1      1                    1            0            0       0   
144   45      1      0                    0            0            0       0   
224   62      1      1                    0            0            0       0   
252   70      0      1                    0            0            0       0   
6     45      1      1                    0            0            0       0   
120   75      1      0                    0            0            0       0   
67    75      1      1                    0            0            0       0   
119   45      0      1                    0            0            0       0   
118   75      1      0                    0            0            0       0   
25    55      1      1                    0            0            0       0   
125   85      1      1                    0            0            0       1   
244   58      1      1                    0            0            0       0   
19    85      0      0                    0            0            0       0   
77    75      1      1                    0            0            0       0   
216   55      1      0                    0            0            0       1   
90    75      1      0                    0            0            0       0   
208   45      1      0                    0            0            0       0   
93    55      1      0              

In [31]:
X_train = train[['age', 'fever', 'cough', 'shortness of breath', 'sore throat', 'muscle pain', 'nausea', 'diarrhoea', 'fatigue', 'vomiting', 'headache'] ].to_numpy()
X_test = test[['age', 'fever', 'cough', 'shortness of breath', 'sore throat', 'muscle pain', 'nausea', 'diarrhoea', 'fatigue', 'vomiting', 'headache'] ].to_numpy()

In [32]:
X_train

array([[75,  1,  0, ...,  0,  0,  0],
       [65,  0,  0, ...,  1,  0,  0],
       [55,  0,  0, ...,  0,  0,  0],
       ...,
       [65,  1,  0, ...,  1,  1,  0],
       [65,  1,  0, ...,  1,  0,  0],
       [35,  1,  0, ...,  0,  0,  0]], dtype=int64)

In [33]:
Y_train = train[['output'] ].to_numpy().reshape(216,)
Y_test = test[['output'] ].to_numpy().reshape(54,)

In [34]:
Y_train

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression()

In [37]:
inputFeatures = [26, 0,1,0,0,1,0,0,0,0,0,]
infProb =clf.predict_proba([inputFeatures])[0][1]

In [38]:
infProb

0.6523590194627917